### PR TITLE
Less deep docs

### PR DESCRIPTION
**Pull request by fabiand**
Previously you needed a lot of clicks to get to some docs or examples.
With this restructuring the number of clicks is reduced.

Based on #27 

Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

### CODE REVIEW

**Comment by mpolednik** [comment]
I believe @phoracek wanted to keep this structure to scale with whatever networking needs.

**Comment by fabiand** [comment]
Right.

But who do you want to do the readmes for - for the structure or for the users? :)

All I want to say, maybe it's more worth to be click friendl and discoverable than a good structure. Just my 2ct.

**Comment by mpolednik** [comment]
Maybe then it makes sense to also rename the docs themselves (e.g. KVM is fine, VFIO could be "device assignment"...). That isn't the scope of this PR nevertheless, so assuming Petr doesn't object and we merge the base it's fine by me.

**Comment by fabiand** [comment]
Updated.

**Comment by phoracek** [comment]
Looks good to me

**Comment by fabiand** [comment]
Updated

**Review by mpolednik — APPROVED** [review]

**Pull request merged**
