### PR TITLE
org update

### PR DESCRIPTION
**Pull request by mpolednik**
Now that the code is under KubeVirt repository, we need to make several changes to remove the personal references and instead refer to the organization itself.

Main points are import path changes and resourceNamespace changes.

### CODE REVIEW

**Comment by mpolednik** [comment]
cc @fabiand 

Try to overlook the number of removed lines; I've decided to commit the vendor dependencies and now pruning has found a lot of them to be unnecessary.

**Comment by rmohr** [comment]
@mpolednik since we have a fresh import here and no-one uses this repo so far, consider a force-update of the master branch, where you do the prune directly on the commits where you added the vendor dependencies ...

**Comment by fabiand** [comment]
OTOH we can just merge this commit.

**Comment by mpolednik** [comment]
I've gone with Roman's suggestion; just merging this commit would lead to huge repository. This way, we have a somewhat clean start.

**Pull request closed without merging**
