### PR TITLE
fix version to kubernetes 1.9

### PR DESCRIPTION
**Pull request by phoracek**
As a follow up, 1.9 branch will be created and master will continue on 1.10.

Signed-off-by: Petr Horacek <phoracek@redhat.com>

### CODE REVIEW

**Comment by fabiand** [comment]
Hey Petr - What do you need to move this forward?

**Comment by phoracek** [comment]
Hi @fabiand, I need to run at least one of our plugins to verify. Then we can migrate master to 1.10, it requires minimal efforts (v1beta1 is a bit different, but not a big deal).

**Comment by phoracek** [comment]
@fabiand do you think we could just abandon this? 1.10 is not backward compatible, is it worth keeping 1.9 maintained?

**Comment by fabiand** [comment]
No. Let's move to 1.10.
Sounds good?

**Pull request closed without merging**
